### ISSUE TITLE
Instructor Feedback - Problem Statement, Solution, and Project Plan

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jtschiss/zipCodeLocationSearchApi#1]
Hi Team!  Nice job with your problem statement. I'm looking forward to seeing this in action!

- [ ] Regarding _"user-friendly interface that allows the user to enter two pieces of data: a zip code, and a type of good or service to search for within that zip code"_   Remember that the main goal of the team project is to build an API that anyone could consume.  Think about the web services that you practiced with in week 8: [swapi](https://swapi.dev), [petstore api](https://petstore.swagger.io), and [zip code api](https://www.zipcodeapi.com). The core "business" here is to provide restful resources and operations.
- [ ] You will likely also have a website that serves as the userguide for the API (refer to the examples above) and the website may also allow a user to test out your API.
- [ ] In your readme.md, be sure to document the resources and methods that you will provide on those resources. Refer to my example in slack #team-project for one example. This will help me understand the scope of your api.

Please let me know if when those items are updated, or if you have any questions!
